/**
 * The task engine (§55).
 *
 * A notification informs; a task requires action (§56). Tasks are generated by
 * services and handlers, never by UI code, and every auto-task carries a
 * `dedupKey` so a repeated trigger UPDATES the existing open task rather than
 * duplicating it -- backed by a partial unique index, so even a handler bug
 * cannot produce two.
 */
import type pg from 'pg';
import type { CommandScope } from '../write-path.ts';

export type OwnerResolver =
  | { kind: 'user'; userId: string }
  | { kind: 'student_coordinator'; studentId: string }
  | { kind: 'student_coach'; studentId: string }
  | { kind: 'student_supervisor'; studentId: string }
  | { kind: 'quality_pool' }
  | { kind: 'quality_lead' };

async function resolveOwner(tx: pg.PoolClient, r: OwnerResolver): Promise<string | null> {
  switch (r.kind) {
    case 'user':
      return r.userId;
    case 'student_coordinator': {
      const { rows } = await tx.query(
        `SELECT coordinator_user_id FROM student_assignment
         WHERE student_id = $1 AND effective_to IS NULL`,
        [r.studentId],
      );
      return rows[0]?.coordinator_user_id ?? null;
    }
    case 'student_coach': {
      const { rows } = await tx.query(
        `SELECT coach_user_id FROM student_coach_assignment
         WHERE student_id = $1 AND effective_to IS NULL AND coach_user_id IS NOT NULL LIMIT 1`,
        [r.studentId],
      );
      return rows[0]?.coach_user_id ?? null;
    }
    case 'student_supervisor': {
      const { rows } = await tx.query(
        `SELECT g.supervisor_user_id FROM student s
         JOIN cohort_group g ON g.id = s.cohort_group_id WHERE s.id = $1`,
        [r.studentId],
      );
      return rows[0]?.supervisor_user_id ?? null;
    }
    case 'quality_pool':
    case 'quality_lead': {
      const roleKey = r.kind === 'quality_lead' ? 'quality_lead' : 'quality_member';
      const { rows } = await tx.query(
        `SELECT ur.user_id FROM user_role ur JOIN role r ON r.id = ur.role_id
         JOIN app_user u ON u.id = ur.user_id
         WHERE r.key = $1 AND u.status = 'active' AND ur.effective_to IS NULL
         ORDER BY (SELECT count(*) FROM task t
                   WHERE t.owner_user_id = ur.user_id AND t.status IN ('open','in_progress'))
         LIMIT 1`,
        [roleKey],
      );
      return rows[0]?.user_id ?? null;
    }
  }
}

export interface CreateTaskInput {
  studentId?: string | null | undefined;
  cohortId?: string | null | undefined;
  taskType: string;
  ownerResolver: OwnerResolver;
  dueAt: Date;
  source: 'manual' | 'workflow' | 'risk' | 'sla' | 'qa' | 'gig' | 'graduation' | 'escalation';
  dedupKey?: string | undefined;
  originatingEventId?: string | undefined;
  priority?: number | undefined;
}

/**
 * Creates or updates an auto-task.
 *
 * `ON CONFLICT` on the dedup key updates the due date, priority and originating
 * event instead of inserting: a second SLA sweep must sharpen the existing task,
 * not add another row to an already-long queue.
 *
 * An unresolvable owner does not silently drop the work -- it raises a
 * data-quality exception in the system log so the control tower can surface it.
 */
export async function createTask(
  scope: CommandScope,
  input: CreateTaskInput,
): Promise<string | null> {
  const { tx, ctx } = scope;
  const owner = await resolveOwner(tx, input.ownerResolver);

  if (!owner) {
    await tx.query(
      `INSERT INTO system_log (level, component, code, message, context, correlation_id)
       VALUES ('warn', 'tasks', 'OWNER_UNRESOLVED',
               'task owner could not be resolved; work is unowned', $1::jsonb, $2)`,
      [
        JSON.stringify({
          taskType: input.taskType,
          studentId: input.studentId ?? null,
          resolver: input.ownerResolver.kind,
        }),
        ctx.correlationId,
      ],
    );
    return null;
  }

  const { rows } = await tx.query(
    `INSERT INTO task (student_id, cohort_id, task_type, owner_user_id, created_by, priority,
                       due_at, status, source, originating_event_id, dedup_key)
     VALUES ($1,$2,$3,$4,$5,$6,$7,'open',$8,$9,$10)
     ON CONFLICT (dedup_key) WHERE dedup_key IS NOT NULL AND status IN ('open','in_progress')
     DO UPDATE SET due_at = EXCLUDED.due_at,
                   priority = LEAST(task.priority, EXCLUDED.priority),
                   originating_event_id = EXCLUDED.originating_event_id
     RETURNING id`,
    [
      input.studentId ?? null,
      input.cohortId ?? null,
      input.taskType,
      owner,
      ctx.source === 'SYSTEM_JOB' ? null : ctx.actor.userId,
      input.priority ?? 100,
      input.dueAt,
      input.source,
      input.originatingEventId ?? null,
      input.dedupKey ?? null,
    ],
  );
  return rows[0]?.id ?? null;
}

/**
 * Cancels open auto-tasks whose reason has disappeared -- a "chase unresponsive
 * student" task cancels when the student replies. Without this the queue fills
 * with stale work and staff learn to ignore it.
 */
export async function cancelTasksByDedupPrefix(
  scope: CommandScope,
  prefix: string,
  reason: string,
): Promise<number> {
  const { rows } = await scope.tx.query(
    `UPDATE task SET status = 'cancelled', cancel_reason = $2
     WHERE dedup_key LIKE $1 || '%' AND status IN ('open','in_progress')
     RETURNING id`,
    [prefix, reason],
  );
  for (const r of rows) {
    await scope.emit({
      type: 'TASK_CANCELLED',
      subjectType: 'task',
      subjectId: r.id,
      payload: { reason },
    });
  }
  return rows.length;
}

/** Reassignment moves open tasks rather than recreating them (§5, W29). */
export async function reassignTasks(
  scope: CommandScope,
  studentId: string,
  toUserId: string,
): Promise<number> {
  const { rows } = await scope.tx.query(
    `UPDATE task SET owner_user_id = $2
     WHERE student_id = $1 AND status IN ('open','in_progress') AND owner_user_id <> $2
     RETURNING id, owner_user_id`,
    [studentId, toUserId],
  );
  for (const r of rows) {
    await scope.audit({
      module: 'my_work',
      recordType: 'task',
      recordId: r.id,
      action: 'reassign',
      permissionUsed: 'my_work.edit',
      newValue: { ownerUserId: toUserId },
    });
  }
  return rows.length;
}

export async function completeTask(
  scope: CommandScope,
  taskId: string,
  notes?: string,
): Promise<void> {
  const { rows } = await scope.tx.query(
    `UPDATE task SET status = 'completed', completed_at = now(), completion_notes = $2
     WHERE id = $1 AND status IN ('open','in_progress','overdue')
     RETURNING student_id, task_type`,
    [taskId, notes ?? null],
  );
  if (rows.length === 0) return;
  await scope.emit({
    type: 'TASK_COMPLETED',
    subjectType: 'task',
    subjectId: taskId,
    payload: { taskType: rows[0].task_type, studentId: rows[0].student_id },
  });
}

/** A user's queue, urgent and overdue first (§11). */
export async function workQueue(db: pg.Pool | pg.PoolClient, userId: string, limit = 100) {
  const { rows } = await db.query(
    `SELECT t.id, t.task_type, t.priority, t.due_at, t.status, t.student_id,
            s.full_name AS student_name, rm.risk_level, rm.sla_state, rm.stage,
            g.code AS group_code,
            (t.due_at IS NOT NULL AND t.due_at < now()) AS overdue
     FROM task t
     LEFT JOIN student s ON s.id = t.student_id
     LEFT JOIN rm_student_current rm ON rm.student_id = t.student_id
     LEFT JOIN cohort_group g ON g.id = rm.cohort_group_id
     WHERE t.owner_user_id = $1 AND t.status IN ('open','in_progress','overdue')
     ORDER BY overdue DESC, t.priority ASC, t.due_at ASC NULLS LAST
     LIMIT $2`,
    [userId, limit],
  );
  return rows;
}
